spring:
  datasource:
    platform: postgresql
    driverClassName: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}   
    initialize: true
    data: classpath*:data-from-migration.sql,classpath*:data.sql,classpath*:data-gen.sql,classpath*:data-personas.sql
  jpa: 
    show-sql: true
    generate-ddl: true
    properties: 
      hibernate: 
        hbm2ddl: 
          auto: update
        format_sql: true
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
flyway:
  locations: classpath:migration
  schemas: public
  validate-on-migrate: false
  baseline-on-migrate: true