spring:
  datasource:
    initialize: true
    data: classpath*:data-from-migration.sql,classpath*:data.sql,classpath*:data-gen.sql,classpath*:data-personas.sql
  jpa: 
    properties: 
      hibernate: 
        hbm2ddl: 
          auto: update
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
flyway:
  locations: classpath:migration
  schemas: public
  validate-on-migrate: false
  baseline-on-migrate: true
---
spring:
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  profiles: dev
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate.format_sql: true
  datasource:
    platform: postgresql
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/telemetria
    username: postgres
    password: postgres
  cache:
    cache-names: person
    guava:
      spec: maximumSize=10,expireAfterAccess=60s
---
spring:
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  profiles: cloud
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate.format_sql: true
  datasource:
    platform: postgresql
    driverClassName: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  cache:
    cache-names: person
    guava:
      spec: maximumSize=10,expireAfterAccess=60s